package main

import (
	"maktabkhoone/handlers"

	"github.com/gin-gonic/gin"
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "github.com/swaggo/gin-swagger/example/basic/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

var router *gin.Engine

// @title Blueprint Swagger API
// @version 1.0
// @description Swagger API for Golang Project Blueprint.
// @termsOfService http://swagger.io/terms/
// @contact.name API Support
// @contact.email martin7.heinz@gmail.com
// @license.name MIT
// @license.url https://github.com/MartinHeinz/go-project-blueprint/blob/master/LICENSE
// @BasePath /api/v1
func main() {
	router = gin.New()
	// The url pointing to API definition
	url := ginSwagger.URL("127.0.0.1:2900/swagger/doc.json") // The url pointing to API definition
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))
	initRoute()
	router.Run(":2900") // listen and serve on 0.0.0.0:8080 (for windows "localhost:8080")
}

func initRoute() {
	// Group persons related routes together
	//router.Use(CORSMiddleware())
	personsRoutes := router.Group("/validation")
	{
		// Handle GET requests at /persons/view/:person_name
		personsRoutes.GET("/national_code/", handlers.IsValidNationalCode)
		// Handle POST requests at /persons/add
	}
}
